### ISSUE TITLE
Is there any performance comparison avaiable?

### ISSUE THREAD

**Issue by hitdshu** [MinoruSekine/libfixedpointnumber#216]
Hi,

Thanks for your excellent project. Is there any performance comparison avaiable? Like fixed vs. float, fixed vs. double, etc..

Deshun

**Comment by MinoruSekine** [comment]
@hitdshu I'm very sorry for missing this ticket.


> Is there any performance comparison avaiable? Like fixed vs. float, fixed vs. double, etc..

No.
Those comparison must be there because we can determine which numeric type is suitable.

But I think there are no doubt that...

- On processor like x64 which has hardware floating point SIMD operations and better SIMD usage, `float` or `double` will be faster than `fixed`
  - Of course they have also better accuracy
- On processor which has no FPU, `fixed` can be faster than emulated `float` and `double`

I have to say "Performance comparison should be available" again.

**Comment by hitdshu** [comment]
Wow, thanks for your reply.....

You're right. Through some search in the web, I found that FPU can make operations of floats as fast as integers. And fixed float might should be used in embbed systems where theres isn't a FPU there....

Thanks for  your help. Have a nice day.
Deshun
